services:

  nginx:
    image: nginx:1.27.2-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: task-php
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: password